### ISSUE TITLE
The link of collected json file

### ISSUE THREAD

**Issue by Baicheng42** [DonDominic/MP2Net#2]
Thanks for your great work!

The link to the collected json file you shared seems to be not working and I am not able to open it.

Could you please check it, Thanks!

**Comment by DonDominic** [comment]
It works fine for me, maybe you should use a VPN to open the onedrive link.

If you are unable to use VPN, please let me know and I will upload a Baidu Netdisk link.

**Comment by Baicheng42** [comment]
It works when using VPN. Thanks again!
