### ISSUE TITLE
A question about object association at different time steps

### ISSUE THREAD

**Issue by lebron-2016** [DonDominic/MP2Net#3]
Dear author,

In `testDis.py` , I found that you used Kalman filter when predicting the state of the target in the next frame, instead of the `tracking_dis` predicted by the model. Why can't we directly use the offset predicted by the model? What is the significance of the offset(or inter-frame displacement) of the target here?

Thanks!!

**Comment by DonDominic** [comment]
Thanks for your attention to our work.

In our previous experiments, we found that incorporating a Kalman filter results in more stable tracking performance compared to using only inter-frame displacement. Consequently, we released this version that combines both the Kalman filter and inter-frame displacement. Additionally, we provided a test using the Kalman filter (SORT) alone in the 'testTrackingSort.py' script. You might find it helpful to run this testing script to see the impact of inter-frame displacement clearly.

**Comment by lebron-2016** [comment]
> Thanks for your attention to our work.
> 
> In our previous experiments, we found that incorporating a Kalman filter results in more stable tracking performance compared to using only inter-frame displacement. Consequently, we released this version that combines both the Kalman filter and inter-frame displacement. Additionally, we provided a test using the Kalman filter (SORT) alone in the 'testTrackingSort.py' script. You might find it helpful to run this testing script to see the impact of inter-frame displacement clearly.

Thanks for your quick reply!

I have three more questions that I would like to confirm. 
1. Are you just using the inter-frame offset as a result correction? (as shown below)

![image](https://github.com/DonDominic/MP2Net/assets/80045218/1b9421d2-873b-4470-b6c3-fe1ebeab452f)

2. Are you only using Kalman filter when predicting the state of the object in the next frame?

3. About `testTrackingSort.py`, is it equivalent to modifying `testDis.py` as follows？

![image](https://github.com/DonDominic/MP2Net/assets/80045218/c2e68e6a-34a0-4424-b972-f14c570877f2)

Thanks!!

**Comment by DonDominic** [comment]
Yes, for questions 1 and 2, in this setting we use inter-frame displacement as result correction and incorporate the Kalman filter to conduct state updates.
For question 3, that's correct.

**Comment by lebron-2016** [comment]
> Yes, for questions 1 and 2, in this setting we use inter-frame displacement as result correction and incorporate the Kalman filter to conduct state updates. For question 3, that's correct.

Got it! Thanks!
