### ISSUE TITLE
Details about calculating FPS

### ISSUE THREAD

**Issue by lebron-2016** [DonDominic/MP2Net#7]
Dear author,

How did you calculate the FPS? What is the relevant experimental configuration?

Looking forward to your reply.

Thanks.

**Comment by DonDominic** [comment]
@lebron-2016 We simply tested it on SatVideoDT and calculated the average frame rate under the overall sequences as FPS.

Hope this finds you well.

**Comment by lebron-2016** [comment]
> @lebron-2016 We simply tested it on SatVideoDT and calculated the average frame rate under the overall sequences as FPS.
> 
> Hope this finds you well.

Hi, do you mean the method of dividing the total test time by the number of test images? I used a single TITAN RTX to perform inference on the SatVideoDT dataset using `mp2net_resnet`. The timing is shown in the following figure:

![image](https://github.com/DonDominic/MP2Net/assets/80045218/bf10e5c3-4b2e-40be-9d3d-7af6a34938ee)

The calculated FPS is 1.2, which is quite different from the 2.5 in the paper. Could you provide more details? 

In addition, how is `FLOPS` calculated in the paper?

Thanks for your help!

**Comment by DonDominic** [comment]
@lebron-2016 Please check if there are other programs occupying computing resources and whether the hard disk used is SSD. The calculation process of FLOPs is included in stNet.py.

Hope this finds you well.

**Comment by lebron-2016** [comment]
> @lebron-2016 Please check if there are other programs occupying computing resources and whether the hard disk used is SSD. The calculation process of FLOPs is included in stNet.py.
> 
> Hope this finds you well.

Got it! Thanks!!
